# AWS CloudFormation Template for Automated Incident Response
# Description: 
#   1. Creates Lambda function to isolate compromised EC2 instances and capture disk snapshots
#   2. Saves forensic metadata to S3
#   3. Integrates with GuardDuty alerts (simulated via manual triggers)

AWSTemplateFormatVersion: '2010-09-09'
Description: Foolproof Forensic Automation with Isolation + S3

# Parameters let you customize the deployment without modifying the template
Parameters:
  S3BucketName:
    Description: Name of your S3 bucket to store forensic metadata
    Type: String
    Default: "ashiq-forensics-ap-southeast-1"

  IsolationSGId:
    Description: ID of the Security Group used to isolate a compromised EC2 instance
    Type: String
    Default: "sg-03355d8255b7bcbb4"

  LambdaCodeS3Bucket:
    Description: Name of the S3 bucket that contains the zipped Lambda function code
    Type: String

  LambdaCodeS3Key:
    Description: S3 key (path) to the zipped Lambda function code (e.g. lambda/function.zip)
    Type: String

Resources:

  # IAM role to allow Lambda to perform EC2 and S3 actions
  ForensicLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: ForensicPermissions
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ec2:DescribeInstances        # Required to look up instance info
                  - ec2:DescribeVolumes         # Needed to find attached volumes
                  - ec2:CreateSnapshot          # For creating EBS snapshots
                  - ec2:ModifyInstanceAttribute # To attach the isolation security group
                  - s3:PutObject                # Upload metadata to S3
                  - s3:GetBucketLocation        # Optional sanity check
                Resource: "*"

  # Lambda function that performs auto-isolation and forensic logging
  IncidentHandlerLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: IncidentHandler
      Handler: incident_handler.lambda_handler     # Format: <filename>.<function>
      Runtime: python3.8
      Timeout: 120
      Role: !GetAtt ForensicLambdaRole.Arn
      Environment:
        Variables:
          S3_BUCKET: !Ref S3BucketName             # Bucket to store forensic evidence
          ISOLATION_SG: !Ref IsolationSGId         # Security Group for isolation
      Code:
        S3Bucket: !Ref LambdaCodeS3Bucket
        S3Key: !Ref LambdaCodeS3Key

Outputs:
  LambdaFunctionName:
    Description: "Name of the Lambda function created"
    Value: !Ref IncidentHandlerLambda

